// Generated by Wrangler by running `wrangler types`

interface Env {
	TOKENS: KVNamespace;
	STORY_POINT_LABEL_NAME: "story-point";
	SESSION_DO: DurableObjectNamespace<import("./src/worker/index").SessionDO>;
	DB: D1Database;
	ASSETS: Fetcher;
}
